### PR TITLE
Add --stackname flag

### PR DESCRIPTION
**Pull request by refractalize**
This change adds a `--stackname` switch to the command line to override the default one constructed from the project name + stage.

### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `master`
- [x] Made sure tests pass (run `npm it` from the repo root)
- [x] Expanded test coverage related to your changes:
  - [x] Added and/or updated unit tests (if appropriate)
  - [x] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [x] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [ ] Summarized your changes in `changelog.md`
- [ ] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by ryanblock** [comment]
Interesting! What's the problem we're trying to solve here? Why would Architect Deploy be used against a CF stack Architect didn't create?

**Comment by refractalize** [comment]
> Interesting! What's the problem we're trying to solve here? Why would Architect Deploy be used against a CF stack Architect didn't create?

We're deploying into an environment where we want to have better control over the environment name, i.e. not just `...Staging` but also other names such as, in our case `Int`.

**Comment by ryanblock** [comment]
Ah ok! And just to be sure, you're aware of the `--name` flag? Is that somehow not meeting the need here?
- https://arc.codes/docs/en/reference/cli/deploy
- https://github.com/architect/deploy/blob/main/src/sam/index.js#L57-L59

**Comment by refractalize** [comment]
> Ah ok! And just to be sure, you're aware of the --name flag?

Yeah I was and actually that would work for our case, thanks!

**Comment by refractalize** [comment]
> Ah ok! And just to be sure, you're aware of the --name flag? Is that somehow not meeting the need here?

Actually it turns out we do need this. We'd like to have full control over the name, not just append something to the end of the generated name. `--name Name` will just make `AppStagingName` but we want the stack to be called `AppName`.

I'm going to reopen this if you don't mind...

**Comment by refractalize** [comment]
For context we have specific naming requirements for CF stacks in our test and prod environments. While that might be particular to our situation, it doesn't seem too unusual to want to override the default stack name provided by arc.

**Comment by refractalize** [comment]
I'm closing this in favour of #368. Somehow my fork was deleted and recreating the fork didn't seem to up date this PR with any new changes.

**Pull request closed without merging**
